### ISSUE TITLE
Using RuleSet in Web API

### ISSUE THREAD

**Issue by joaopgrassi** [jasonmitchell/fluentvalidation-webapi-autofac#1]
Hello!
I was following your article here:
http://json.codes/blog/integrating-fluent-validation-with-aspnet-web-api/

Everything worked perfectly, but I was wondering if there's any way I can also use the RuleSet inside my validation class. I tried doing this in your sample project:

```
public class PersonValidator : AbstractValidator<Person>
{
    public PersonValidator()
    {
        //RuleFor(x => x.FirstName).NotEmpty();
        //RuleFor(x => x.LastName).NotEmpty();

        RuleSet("CreatePerson", () =>
        {
            RuleFor(item => item.FirstName)
                .NotEmpty()
                .WithMessage("First name should not be empty");
        });
    }
}
```

The PersonValidation is fired (I can see that during debug) but the ModelState is always valid (true). Did you find a way to do this? I have being trying this for days now. Thanks!

**Comment by jasonmitchell** [comment]
I think what you need is this: https://github.com/JeremySkinner/FluentValidation/blob/master/src/FluentValidation.Mvc3/CustomizeValidatorAttribute.cs

Unfortunately that's in the MVC package and not Web API - I'm not sure how you would make use of RuleSets in WebAPI.

**Comment by joaopgrassi** [comment]
Yes, I'm afraid I hit a brick wall. Thanks anyway!
